"use client";

// import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Define dashboard routes (or any route where you want to hide navbar/footer)
  const isDashboardRoute = pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className="w-full bg-white">
        <SessionProviderWrapper>
          {/* Hide Navbar if on dashboard routes */}
          {!isDashboardRoute && (
            <div className="mb-[84px]">
              <Navbar />
            </div>
          )}

          <main className="bg-white">{children}</main>

          {/* Hide Footer if on dashboard routes */}
          {!isDashboardRoute && <Footer />}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
